### PR TITLE
addressed ui/ux issues in activity/monitoring view and cluster dropdown

### LINKED ISSUE #295: BUG: Trim whitespace from username
Currently, whitespaces are not trimmed in the connection modal. If a user accidentally enters a space before or after their username/password, the connection will fail.

### PR DESCRIPTION
**Pull request by nassery318**
## Description

Include a summary of the change.

1. Trim whitespace from connection fields (in connection and edit connection forms)
2. Moved the warning to avoid obstructing buttons (user can minimize it)
3. Added stop all button and functionality to the monitor warning banner
4. Start Monitoring button renamed to Start MONITOR 
5. Changed from Monitoring view to Activity in the App Header/Sidebar
6. Cluster dropdown fixed with scrolling ability and fixed search input

### Change Visualization

Include a screenshot/video of before and after the change.

https://github.com/user-attachments/assets/94d9d80b-2892-4415-b317-bfd301b44573

### CODE REVIEW

File: apps/frontend/src/components/ui/monitor-warning-banner.tsx [hunk 1]
```diff
@@ -65,6 +65,18 @@ export function MonitorWarningBanner() {
...
+              {runningConnections.length > 1 && (
+                <span
+                  className="text-destructive ml-2 underline cursor-pointer hover:text-destructive/80"
+                  onClick={() => {
+                    runningConnections.forEach(({ connectionId }) => {
+                      handleStop(connectionId)
+                    })
+                  }}
+                >
+                  Stop All
```
Comment (ravjotbrar) [inline apps/frontend/src/components/ui/monitor-warning-banner.tsx]: Let's stop monitoring for all nodes the same way we start monitoring for all nodes, in the backend. The frontend may not always be in sync with the current metrics servers running

Comment (arseny-kostenko) [reply apps/frontend/src/components/ui/monitor-warning-banner.tsx]: Agree. And let's remove the ability to stop individual nodes. All or nothing

**Comment by ArgusLi** [comment]
This will close https://github.com/valkey-io/valkey-admin/issues/295

File: apps/frontend/src/components/ui/monitor-warning-banner.tsx [hunk 2]
```diff
@@ -33,11 +33,21 @@ export function MonitorWarningBanner() {
...
   if (runningConnections.length === 0) return null
 
-  const handleStop = (connectionId: string) => {
-    dispatch(saveMonitorSettingsRequested({
-      connectionId,
-      monitorAction: MONITOR_ACTION.STOP,
-    }))
+  const handleStopAll = () => {
+    if (clusterId) {
+      dispatch(saveMonitorSettingsRequested({
```
Comment (ravjotbrar) [inline apps/frontend/src/components/ui/monitor-warning-banner.tsx]: Are we able to call monitorRequested directly? And why do we need an else block?

Comment (nassery318) [reply apps/frontend/src/components/ui/monitor-warning-banner.tsx]: Addressed

File: apps/frontend/src/components/ui/monitor-warning-banner.tsx (hunk 1 above)
Comment (nassery318) [reply apps/frontend/src/components/ui/monitor-warning-banner.tsx]: addressed

File: apps/frontend/src/components/ui/monitor-warning-banner.tsx (hunk 2 above)
Comment (ravjotbrar) [reply apps/frontend/src/components/ui/monitor-warning-banner.tsx]: Can we not call monitorRequested instead of saveMonitorSettings?

File: apps/server/src/actions/monitorAction.ts [hunk 3]
```diff
@@ -47,9 +47,24 @@ const sendMonitorError = (
...
+    } else if (clusterId) {
+      // for cluster nodes: fan out to all nodes in the cluster registry that have an active metrics server.
+      connectionIds = Object.keys(clusterNodesRegistry[clusterId as string] ?? {}).filter((id) => metricsServerMap.has(id))
+      resolvedAction = monitorAction as MonitorAction
+    } else {
+      // Standalone start/status: act on the single specified connection.
+      // Standalone stop is handled by stop_all above.
+      connectionIds = [connectionId]
+      resolvedAction = monitorAction as MonitorAction
+    }
```
Comment (ravjotbrar) [inline apps/server/src/actions/monitorAction.ts]: We shouldn't need a new monitor action. Stop should be called already for each node belonging to that cluster.

Comment (ravjotbrar) [reply apps/server/src/actions/monitorAction.ts]: You could probably remove all of the changes here and just dispatch stop action from the frontend. Let me know if that works.

**Review by arseny-kostenko — APPROVED** [review]
