### PR TITLE
fixed the cluster and node connect button states

### LINKED ISSUE #317: BUG: Add connection state to all connect buttons
Currently, if a user tries to connect using the cluster Connect button or the power icons in cluster topology, there's no connection state. If a user tries to connect with these buttons, they are not given any feedback if the connection is still connecting or if there is an error.

### PR DESCRIPTION
**Pull request by nassery318**
## Description

Include a summary of the change.

1. Cluster connect button state fixed and shows Spinner when connecting 
2. Node connect button state fixed and shows Spinner when connecting 
3. Both above cases will show a toast when there is a connection error

### Change Visualization

Include a screenshot/video of before and after the change.

https://github.com/user-attachments/assets/4df48ade-40a1-4b52-8b26-d6286e5a8d90

### CODE REVIEW

File: apps/frontend/src/components/cluster-topology/cluster-node.tsx [hunk 1]
```diff
@@ -166,17 +168,25 @@ export function ClusterNode({
...
-                  className={cn(
-                    "rounded-full p-0.5",
-                    isConnected && "text-green-500 bg-green-100",
-                    !isConnected && isDisabled && "text-gray-300 cursor-not-allowed bg-gray-100",
-                    !isConnected && !isDisabled && "text-gray-400 cursor-pointer bg-gray-100 hover:text-gray-600",
-                  )}
-                  onClick={isDisabled ? undefined : handleNodeConnect}
-                  size={18}
-                />
+              <CustomTooltip content={isConnected ? "Connected" : isConnecting ? "Connecting..." : isError ? "Connection failed — click to retry" : isDisabled ? `Max connections of ${MAX_CONNECTIONS} reached` : "Not Connected"}>
```
Comment (arseny-kostenko) [inline apps/frontend/src/components/cluster-topology/cluster-node.tsx]: that's a long string, can you extract and/or format it to fit 120 chars?

File: apps/frontend/src/components/cluster-topology/cluster-node.tsx [hunk 2]
```diff
@@ -166,17 +168,25 @@ export function ClusterNode({
...
+                {isConnecting ? (
+                  <Loader2
+                    className="animate-spin text-gray-500"
+                    size={21}
+                  />
+                ) : (
+                  <PowerIcon
+                    className={cn(
+                      "rounded-full p-0.5",
+                      isConnected && "text-green-500 bg-green-100",
```
Comment (arseny-kostenko) [inline apps/frontend/src/components/cluster-topology/cluster-node.tsx]: q: does this (and below) look find in dark mode?

File: apps/frontend/src/components/cluster-topology/cluster-node.tsx [hunk 3]
```diff
@@ -166,17 +168,25 @@ export function ClusterNode({
...
+                      isError && "text-red-500 bg-red-100 cursor-pointer hover:text-red-600",
+                      !isConnected && !isError && isDisabled && "text-gray-300 cursor-not-allowed bg-gray-100",
+                      !isConnected && !isError && !isDisabled && "text-gray-400 cursor-pointer bg-gray-100 hover:text-gray-600",
+                    )}
+                    onClick={isDisabled ? undefined : handleNodeConnect}
```
Comment (arseny-kostenko) [inline apps/frontend/src/components/cluster-topology/cluster-node.tsx:192]: let's replace undefined with `() => false` or `R.F` so onClick always accepts a `function` instead of `function?`

**Review by arseny-kostenko — APPROVED** [review]
